export const defaultEELabels = {
  close: 'Sulge',
  open: 'Ava',
  remove: 'Eemalda',
  cancel: 'Tühista',
  search: 'Otsi',
  date: 'Kuupäev',
  time: 'Kellaeg',
  required: 'Kohustuslik väli',
  'header.open': 'Ava menüü',
  'header.close': 'Sulge menüü',
  'header.logout': 'Logi välja',
  'file-upload.add': 'Lisa Manus',
  'time-picker.add-one': 'Lisa üks',
  'time-picker.substract-one': 'Eemalda üks',
  'modal.close': 'Sulge modaal',
  'stepper.completed': 'Lõpetatud',
  'stepper.not-completed': 'Lõpetamata',
  'table.loading': 'Tabel laeb',
  'table.filter': 'Filtreeri',
  'table.filter.select-all': 'Vali kõik',
  'table.filter.remove-all': 'Eemalda valikud',
  'table.no-spaces': 'Tekst ei tohi alata tühikutega',
  'table.min-length': 'Sisesta vähemalt 3 tähemärki',
  'table.open-sub-row': 'Ava alamrida',
  'table.close-sub-row': 'Sulge alamrida',
  'table.select-all': 'Vali kõik',
  'table.select-row': 'Vali rida',
  'table.sort.asc': 'Sorteeri kasvavalt',
  'table.sort.desc': 'Sorteeri kahanevalt',
  'table.sort.remove': 'Eemalda sorteerimine',
  'pagination.prev-page': 'Eelmine leht',
  'pagination.next-page': 'Järgmine leht',
  'pagination.results': 'tulemust',
  'pagination.page-size': 'Lehe suurus',
  'truncate.see-more': 'Näita rohkem',
  'truncate.see-less': 'Näita vähem',
  'datepicker.toolbarTitle': 'Vali kuupäev',
  'timepicker.toolbarTitle': 'Vali kellaeg',
  'datetimepicker.toolbarTitle': 'Vali kuupäev ja kellaeg',
};
